# Generated by Django 6.1.1 on 2026-09-20 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toppings',
            name='text',
            field=models.CharField(max_length=200),
        ),
    ]
