citys = ['Hefei','Beijing','Tokyo','Chengdu','Nanjing']
print(citys)
print(sorted(citys))
print(citys)
print(sorted(citys,reverse=True))
print(citys)
citys.reverse()
print(citys)
citys.sort()
print(citys)
citys.sort(reverse=True)
print(citys)